language: php
sudo: required
dist: trusty
php:
- '7.2'
- '7.3'
before_script:
- sudo rm -f /etc/localtime
- sudo ln -s /usr/share/zoneinfo/UTC /etc/localtime
install:
- composer config version `echo $TRAVIS_BRANCH | sed -e's/x/x-dev/g'`
- travis_retry composer install --no-interaction
- composer global require drush/drush:^8.1.0
- composer info -i
script:
- export PATH="$PATH:$PWD/vendor/bin:$HOME/.config/composer/vendor/bin"
- "./vendor/bin/phpunit"
- "./bin/drutiny policy:list"
- "./bin/drutiny profile:run test @none"
- "./bin/drutiny profile:run test @none --uri=site1.test --uri=site2.test -f html -o multisite.test"
- "./bin/drutiny policy:audit Test:Pass @none"
- "./bin/drutiny audit:run \"Drutiny\\Audit\\AlwaysPass\" @none"
deploy:
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.0.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.1.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.2.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.3.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.4.x
    php: 7.2
notifications:
  email:
    on_success: never
    on_failure: always
