language: php
sudo: false
dist: trusty
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - sudo rm -f /etc/localtime
  - sudo ln -s /usr/share/zoneinfo/UTC /etc/localtime

install:
  - travis_retry composer install --no-interaction
  - composer require drush/drush:^8.1.0
  - composer info -i

script:
  - export PATH="$PATH:$PWD/bin"
  - which drush
  - ./vendor/bin/phpunit
  - ./bin/drutiny policy:list
  - ./bin/drutiny profile:run test @none
  - ./bin/drutiny profile:run test @none --uri=site1.test --uri=site2.test -f html -o multisite.test

# Configure email notifications
notifications:
  email:
    on_success: never
    on_failure: always
