language: php
sudo: required
dist: trusty
php:
- '5.6'
- '7.0'
- '7.1'
before_script:
- sudo rm -f /etc/localtime
- sudo ln -s /usr/share/zoneinfo/UTC /etc/localtime
install:
- travis_retry composer install --no-interaction
- composer require drush/drush:^8.1.0
- composer info -i
script:
- export PATH="$PATH:$PWD/vendor/bin"
- "./vendor/bin/phpunit"
- "./bin/drutiny policy:list"
- "./bin/drutiny profile:run test @none"
- "./bin/drutiny profile:run test @none --uri=site1.test --uri=site2.test -f html -o multisite.test"
- "./bin/drutiny policy:audit Test:Pass @none"
- "./bin/drutiny audit:run Drutiny\\Audit\\AlwaysPass @none"
deploy:
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.0.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.1.x
    php: 7.1
- provider: script
  script: ./docs/deploy.sh
  skip_cleanup: true
  on:
    branch: 2.2.x
    php: 7.1
notifications:
  email:
    on_success: never
    on_failure: always
