site_name: Drutiny
site_dir: docs_html
repo_url: 'https://github.com/drutiny/drutiny'
site_description: 'This is a generic Drupal site auditing and optional remediation tool.'
theme: material
google_analytics:
    - UA-116046012-1
    - drutiny.github.io
extra_css:
    - css/tweaks.css
pages:
    -
        Home: index.md
    -
        Usage:
            -
                Reports: reports.md
            -
                Plugins: plugins.md
            -
                Contributing: CONTRIBUTING.md
    -
        'API Documentation':
            -
                Audit: audits.md
            -
                Sandbox: sandbox.md
            -
                Policy: policy.md
            -
                Profile: profiles.md
    -
        'Policy Library':
            -
                Overview: policy-library.md
            -
                drutiny/drutiny: policies/drutiny-drutiny.md
            -
                drutiny/acquia: policies/drutiny-acquia.md
            -
                drutiny/plugin-drupal-8: policies/drutiny-plugin-drupal-8.md
            -
                drutiny/plugin-drupal-7: policies/drutiny-plugin-drupal-7.md
            -
                drutiny/plugin-distro-common: policies/drutiny-plugin-distro-common.md
            -
                drutiny/cloudflare: policies/drutiny-cloudflare.md
            -
                drutiny/http: policies/drutiny-http.md
